version: "3"
services:
  db:
    image: postgres:12-bullseye
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
  app:
    image: my-node-app
    ports:
      - 13000:3000
